"""Runtime configuration, read once from the environment."""
from __future__ import annotations

import os
from dataclasses import dataclass, field
from functools import lru_cache
from typing import List


def _split(value: str) -> List[str]:
    return [item.strip() for item in value.split(",") if item.strip()]


@dataclass(frozen=True)
class Settings:
    secret_key: str = os.getenv("MEDLY_SECRET_KEY", "dev-only-insecure-secret-change-me")
    algorithm: str = "HS256"
    access_token_minutes: int = int(os.getenv("MEDLY_ACCESS_TOKEN_MINUTES", "720"))

    database_url: str = os.getenv("MEDLY_DATABASE_URL", "sqlite:///./medly.db")

    # Teacher uploads (cover art, question images) land here and are served
    # back from /uploads. Use a persisted volume in production.
    upload_dir: str = os.getenv("MEDLY_UPLOAD_DIR", "./data/uploads")

    cors_origins: List[str] = field(
        default_factory=lambda: _split(
            os.getenv("MEDLY_CORS_ORIGINS", "http://localhost:5173,http://127.0.0.1:5173")
        )
    )
    # Deploy platforms hand out a new hostname per preview. Matching by pattern
    # avoids redeploying the API to add each one. Replit previews use
    # *.replit.dev (production) and *.replit.app (classic), Railway uses
    # *.up.railway.app, Vercel uses *.vercel.app.
    cors_origin_regex: str = os.getenv(
        "MEDLY_CORS_ORIGIN_REGEX",
        r"https://.*\.(up\.railway\.app|vercel\.app|replit\.dev|replit\.app)",
    )

    # Containers start with an empty volume, so a fresh deploy has no curriculum
    # and no demo accounts unless the seed runs on boot. Idempotent either way —
    # every seed step skips rows that already exist, so leaving it on for every
    # boot is safe. The one thing it must NOT do is rotate MEDLY_SECRET_KEY,
    # because that would invalidate every stored session on restart.
    seed_on_startup: bool = os.getenv("MEDLY_SEED_ON_STARTUP", "false").lower() in {
        "1", "true", "yes",
    }

    assistant_provider: str = os.getenv("MEDLY_ASSISTANT_PROVIDER", "rules")
    anthropic_api_key: str = os.getenv("ANTHROPIC_API_KEY", "")
    openai_api_key: str = os.getenv("OPENAI_API_KEY", "")

    # --- Gemini ------------------------------------------------------------
    # Server-side only. The key is never sent to the browser: the frontend
    # talks to /api/assistant/chat, and this process talks to Google.
    gemini_api_key: str = os.getenv("GEMINI_API_KEY", "")
    gemini_model: str = os.getenv("GEMINI_MODEL", "gemini-3.5-flash")
    gemini_base_url: str = os.getenv(
        "GEMINI_BASE_URL", "https://generativelanguage.googleapis.com/v1beta"
    )
    gemini_timeout_seconds: float = float(os.getenv("GEMINI_TIMEOUT_SECONDS", "45"))

    # Cost and abuse ceilings. Every one of these is a real limit enforced in
    # code, not a suggestion — an unbounded context window on a paid API is a
    # billing incident waiting to happen.
    ai_max_message_chars: int = int(os.getenv("MEDLY_AI_MAX_MESSAGE_CHARS", "4000"))
    ai_max_output_tokens: int = int(os.getenv("MEDLY_AI_MAX_OUTPUT_TOKENS", "1600"))
    ai_history_turns: int = int(os.getenv("MEDLY_AI_HISTORY_TURNS", "6"))
    ai_max_context_chars: int = int(os.getenv("MEDLY_AI_MAX_CONTEXT_CHARS", "12000"))
    ai_article_context_chars: int = int(os.getenv("MEDLY_AI_ARTICLE_CONTEXT_CHARS", "6000"))
    ai_note_context_chars: int = int(os.getenv("MEDLY_AI_NOTE_CONTEXT_CHARS", "1500"))

    # Per-user request ceiling, counted in this process.
    ai_rate_limit_per_minute: int = int(os.getenv("MEDLY_AI_RATE_LIMIT_PER_MINUTE", "12"))
    ai_rate_limit_per_hour: int = int(os.getenv("MEDLY_AI_RATE_LIMIT_PER_HOUR", "120"))

    inference_engine: str = os.getenv("MEDLY_INFERENCE_ENGINE", "mock")
    onnx_model_path: str = os.getenv("MEDLY_ONNX_MODEL_PATH", "")

    low_confidence_threshold: float = float(os.getenv("MEDLY_LOW_CONFIDENCE_THRESHOLD", "0.70"))

    # Shown on every AI output in the product. Non-negotiable by design.
    disclaimer: str = (
        "Educational use only. This output is generated by a simulated model for "
        "training purposes and must not be used for clinical diagnosis or patient care. "
        "A qualified clinician is responsible for every decision."
    )


@lru_cache
def get_settings() -> Settings:
    return Settings()


settings = get_settings()
