"""Runtime configuration, read once from the environment."""
from __future__ import annotations

import os
from dataclasses import dataclass, field
from functools import lru_cache
from typing import List


def _split(value: str) -> List[str]:
    return [item.strip() for item in value.split(",") if item.strip()]


@dataclass(frozen=True)
class Settings:
    secret_key: str = os.getenv("MEDLY_SECRET_KEY", "dev-only-insecure-secret-change-me")
    algorithm: str = "HS256"
    access_token_minutes: int = int(os.getenv("MEDLY_ACCESS_TOKEN_MINUTES", "720"))

    database_url: str = os.getenv("MEDLY_DATABASE_URL", "sqlite:///./medly.db")

    cors_origins: List[str] = field(
        default_factory=lambda: _split(
            os.getenv("MEDLY_CORS_ORIGINS", "http://localhost:5173,http://127.0.0.1:5173")
        )
    )
    # Deploy platforms hand out a new hostname per preview. Matching by pattern
    # avoids redeploying the API to add each one.
    cors_origin_regex: str = os.getenv(
        "MEDLY_CORS_ORIGIN_REGEX", r"https://.*\.(up\.railway\.app|vercel\.app)"
    )

    # Containers start with an empty volume, so a fresh deploy has no curriculum
    # and no demo accounts unless the seed runs on boot. Idempotent either way.
    seed_on_startup: bool = os.getenv("MEDLY_SEED_ON_STARTUP", "false").lower() in {
        "1", "true", "yes",
    }

    assistant_provider: str = os.getenv("MEDLY_ASSISTANT_PROVIDER", "rules")
    anthropic_api_key: str = os.getenv("ANTHROPIC_API_KEY", "")
    openai_api_key: str = os.getenv("OPENAI_API_KEY", "")

    inference_engine: str = os.getenv("MEDLY_INFERENCE_ENGINE", "mock")
    onnx_model_path: str = os.getenv("MEDLY_ONNX_MODEL_PATH", "")

    low_confidence_threshold: float = float(os.getenv("MEDLY_LOW_CONFIDENCE_THRESHOLD", "0.70"))
    certification_pass_score: int = int(os.getenv("MEDLY_CERTIFICATION_PASS_SCORE", "80"))

    # Shown on every AI output in the product. Non-negotiable by design.
    disclaimer: str = (
        "Educational use only. This output is generated by a simulated model for "
        "training purposes and must not be used for clinical diagnosis or patient care. "
        "A qualified clinician is responsible for every decision."
    )


@lru_cache
def get_settings() -> Settings:
    return Settings()


settings = get_settings()
